<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RACD-002157" name="Search Flight tickets in Firfox" tests="1" failures="1" timestamp="7 Jun 2019 07:33:56 GMT" time="66.541" errors="0">
  <testcase name="SearchTickets" time="51.737" classname="TestClass.ParallelTest_FlightTicketsSearch">
    <failure type="java.lang.AssertionError" message="Test case has been failed">
      <![CDATA[java.lang.AssertionError: Test case has been failed
	at TestClass.ParallelTest_FlightTicketsSearch.SearchTickets(ParallelTest_FlightTicketsSearch.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SearchTickets -->
</testsuite> <!-- Search Flight tickets in Firfox -->
